export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<link rel='shortcut icon' href='/static/favicon.ico'></link>
			<body>{children}</body>
		</html>
	)
}
